project_name: aifiler

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: aifiler
    main: ./cmd/aifiler
    binary: aifiler
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  draft: true

chocolateys:
  - name: aifiler
    title: AI File Assistant
    authors: Aifiler Contributors
    project_url: https://github.com/JoshiMinh/aifiler
    url_template: "https://github.com/JoshiMinh/aifiler/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    description: AI-powered local-first file management copilot.
    summary: Semantic file management with safety-first dry-runs.
    tags: "ai files cli local"

scoops:
  - name: aifiler
    repository:
      owner: JoshiMinh
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    homepage: https://github.com/JoshiMinh/aifiler
    description: AI-powered local-first file management copilot.
    license: MIT
